"""dodano klumnę url_address i job_title do tabeli JobOffer

Revision ID: 63d89c306f5c
Revises: b3c4163ee673
Create Date: 2026-07-21 16:41:01.408418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d89c306f5c'
down_revision: Union[str, Sequence[str], None] = 'b3c4163ee673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_offers', sa.Column('url_address', sa.String(), nullable=False))
    op.add_column('job_offers', sa.Column('job_title', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'job_offers', ['url_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_offers', type_='unique')
    op.drop_column('job_offers', 'job_title')
    op.drop_column('job_offers', 'url_address')
    # ### end Alembic commands ###
