"""dodano ograniczenie on_delete= cascade dla kolumny offer_id w tabeli offer_tech

Revision ID: 893f1d24502d
Revises: 63d89c306f5c
Create Date: 2026-07-31 12:32:50.389977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893f1d24502d'
down_revision: Union[str, Sequence[str], None] = '63d89c306f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('offer_tech_offer_id_fkey'), 'offer_tech', type_='foreignkey')
    op.create_foreign_key(None, 'offer_tech', 'job_offers', ['offer_id'], ['offer_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer_tech', type_='foreignkey')
    op.create_foreign_key(op.f('offer_tech_offer_id_fkey'), 'offer_tech', 'job_offers', ['offer_id'], ['offer_id'])
    # ### end Alembic commands ###
