"""create initial tables

Revision ID: b3c4163ee673
Revises: 
Create Date: 2026-07-16 15:37:57.119540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c4163ee673'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('technologies',
    sa.Column('tech_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tech_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job_offers',
    sa.Column('offer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('type_of_contract', sa.Enum('B2B', 'UOP', name='contracttype'), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=False),
    sa.Column('salary_max', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', name='offerstatus'), nullable=False),
    sa.Column('experience', sa.Enum('JUNIOR', 'MID', 'SENIOR', name='experiencelevel'), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('mode_of_work', sa.Enum('STATIONARY', 'REMOTE', 'HYBRID', name='workmode'), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('last_seen_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_table('offer_history',
    sa.Column('change_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('change_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['job_offers.offer_id'], ),
    sa.PrimaryKeyConstraint('change_id')
    )
    op.create_table('offer_tech',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('tech_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['job_offers.offer_id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['technologies.tech_id'], ),
    sa.PrimaryKeyConstraint('offer_id', 'tech_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_tech')
    op.drop_table('offer_history')
    op.drop_table('job_offers')
    op.drop_table('technologies')
    op.drop_table('companies')
    # ### end Alembic commands ###
